config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :customers
  resources :work_instructions
  resources :procedures

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates :customercode, presence: true
  validates :customercode, uniqueness: { case_sensitive: false }
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true, length: { is: 2 }
  validates :zipcode, presence: true, length: { is: 5 }

end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  attr_accessible :name

  belongs_to :user

  valdates :name, :presence => true

  has_many :work_instruction_procedures
  has_many :work_instructions, :through => :work_instruction_procedures

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :customers
  has_many :work_instructions
  has_many :procedures
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/work_instruction.rb
class WorkInstruction < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :workcode, presence: true, length: { maximum: 4 }
  validates :workcode, uniqueness: { case_sensitive: false }
  validates :description, presence: true

  has_many :work_instruction_procedures
  has_many :procedures, :through => :work_instruction_procedures
end

app/models/work_instruction_procedure.rb
class WorkInstructionProcedure < ActiveRecord::Base
  attr_accessible :work_instruction_id, :procedure_id

  belongs_to :work_instruction
  belongs_to :procedure
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @customer = Customer.all
    @customers_grid = initialize_grid(Customer,
    order: 'customers.id',
    order_direction: 'asc'
    )
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = current_user.customers.create(customer_params)
    if @customer.save
      flash[:success] = 'Customer has been created!'
      redirect_to customers_path
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update_attributes(customer_params)
    if @customer.valid?
      redirect_to customers_path
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :customercode,
    :address, :city, :state, :zipcode)
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @procedure = Procedure.all
  end

  def show
    @procedure = Procedure.find(params[:id])
  end

  def new
    @procedure = Procedure.new
    @work_instructions = WorkInstruction.all
    @procedure.work_instruction_ids = []

  end

  def create
    @procedure = current_user.procedures.create(procedure_params)

    if @procedure.valid?
      flash[:success] = 'Procedure has been created!'
      redirect_to root_path
    else
      @work_instructions = WorkInstruction.all
      render :new, :status => :unprocessable_entity
      @work_instruction_ids.save
    end
  end

  private

  def procedure_params
    params.require(:procedure).permit( :name, :code, [:work_instruction_ids => []])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @customers_grid = initialize_grid(Customer,
    order: 'customers.id',
    order_direction: 'asc'
    )
    @work_instructions_grid = initialize_grid(WorkInstruction,
    order: 'work_instructions.workcode',
    order_direction: 'asc')
  end
end

app/controllers/work_instructions_controller.rb
class WorkInstructionsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @work_instruction = WorkInstruction.all
    @work_instructions_grid = initialize_grid(WorkInstruction,
    order: 'work_instructions.workcode',
    order_direction: 'asc'
    )
  end

  def new
    @work_instruction = WorkInstruction.new
  end

  def create
    @work_instruction = current_user.work_instructions.create(work_instruction_params)
    if @work_instruction.save
      flash[:success] = 'New instructions have been created!'
      redirect_to root_path
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def show
    @work_instruction = WorkInstruction.find(params[:id])
  end

  def edit
    @work_instruction = WorkInstruction.find(params[:id])
  end

  def update
    @work_instruction = WorkInstruction.find(params[:id])
    @work_instruction.update_attributes(work_instruction_params)
    if @work_instruction.valid?
      redirect_to work_instructions_path
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  def destroy
    @work_instruction = WorkInstruction.find(params[:id])
    @work_instruction.destroy
    redirect_to work_instructions_path
  end

  private

  def work_instruction_params
    params.require(:work_instruction).permit(:name, :workcode, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/work_instructions_helper.rb
module WorkInstructionsHelper
end

app/views/customers/edit.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Customer Info</h1>
  <br  />
  <%= simple_form_for @customer do |f| %>
  <%= f.input :name, label: 'Name' %>
  <%= f.input :customercode, label: 'Customer Code'  %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zipcode, label: 'Zip' %>
  <br  />
  <%= f.submit "Submit", class: 'btn btn-primary' %>
  <%= link_to 'Delete Record', customer_path(@customer), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this?' }, :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/customers/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a New Customer</h1>
  <br  />
  <%= simple_form_for @customer, url: customers_path do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :customercode, label: 'Customer Code'  %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zipcode, label: 'Zip' %>
  <br  />
  <%= f.submit "Submit", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/customers/show.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
<h1><%= @customer.name %></h2>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Order Manager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Order Manager', root_path, class: 'navbar-brand' %>/li>

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'New Work Instruction', new_work_instruction_path %></li>
            <li><%= link_to 'New Customer', new_customer_path %></li>
            <li><%= link_to 'New Procedure', new_procedure_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <% end %>
              <li><a href="#">Link</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                </ul>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>

    </body>
    </html>

app/views/procedures/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Create a New Procedure</h1>
  <br />
  <%= simple_form_for @procedure, url: procedures_path do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :code, label: "Code" %>
  <%= f.collection_check_boxes :work_instruction_ids, @work_instructions, :id, :name, :prompt => "Select a work instruction", input_html: { multiple: true}, :value_method => :to_sym %>
    <%= f.collection_select :work_instruction_ids, @work_instructions, :id, :name, :prompt => "Select a work instruction", input_html: { multiple: true}, :value_method => :to_sym %>


<br />
  <br />
  <%= f.submit "Submit", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/procedures/show.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
<%= @procedure.name %>
<%= @procedure.code %>
<%= @procedure.work_instruction_id %>
</div>

app/views/static_pages/index.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2 class = "text-center"> Customers </h2>
  <%= grid(@customers_grid, show_filters: :always) do |g|

    g.column name: 'ID' do |customer|
      customer.id
    end
    g.column  name: 'Company Name' do |customer|
      customer.name
    end
    g.column name: 'Code' do |customer|
      customer.customercode
    end
    g.column  name: 'Address' do |customer|
      customer.address
    end
    g.column name: 'City' do |customer|
      customer.city
    end
    g.column name: 'State' do |customer|
      customer.state
    end
    g.column name: 'Zip' do |customer|
      customer.zipcode
    end
    g.column name: 'Edit?' do |customer|
      link_to('Modify', edit_customer_path(customer))
    end

  end %>

</div>


<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2 class="text-center">Work Instructions</h2>
  <%= grid(@work_instructions_grid, show_filters: :always) do |g|

    g.column name: 'Code' do |work_instruction|
      work_instruction.workcode
    end
    g.column  name: 'Process' do |work_instruction|
      work_instruction.name
    end
    g.column name: 'Description' do |work_instruction|
      work_instruction.description
    end

    g.column name: 'Edit?' do |work_instruction|
          link_to('Modify', edit_work_instruction_path(work_instruction))
    end

  end %>

</div>

app/views/work_instructions/edit.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Work Instruction</h1>
  <%= simple_form_for @work_instruction do |f| %>
  <%= f.input :name, label: 'Name' %>
  <%= f.input :workcode, label: 'Code' %>
  <%= f.input :description %>
  <br  />
  <%= f.submit "Submit", class: 'btn btn-primary' %>
  <%= link_to 'Delete Record', work_instruction_path(@work_instruction), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this record?' }, :class => 'btn btn-danger' %>
  <% end %>
  <br  />

app/views/work_instructions/index.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <%= grid(@work_instructions_grid, show_filters: :always) do |g|

    g.column name: 'Code' do |work_instruction|
      work_instruction.workcode
    end
    g.column  name: 'Process' do |work_instruction|
      work_instruction.name
    end
    g.column name: 'Description' do |work_instruction|
      work_instruction.description
    end

    g.column name: 'Edit?' do |work_instruction|
          link_to('Modify', edit_work_instruction_path(work_instruction))
    end

  end %>

</div>

app/views/work_instructions/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a New Work Instruction</h1>
  <br  />
  <%= simple_form_for @work_instruction, url: work_instructions_path do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :workcode, label: 'Work Instruction Code' %>
  <%= f.input :description %>
  <br  />
  <%= f.submit "Submit", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/work_instructions/show.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
<h1><%= @work_instruction.name %></h2>


</div>